Use shutil.move instead of os.rename in diff-clang-format.py
Fix the following issue encountered by @sslattery:
Error: [Errno 18] Invalid cross-device link